import { Plus, Minus } from 'lucide-react';
import type { Transaction, TransactionType } from '../../types/transaction';
import { TransactionList } from '../accounting/TransactionList';
function greeting(){const h=new Date().getHours(); if(h<11)return '早安'; if(h<14)return '午安'; if(h<18)return '下午好'; return '晚安';}
function isToday(date:string){return date===new Date().toISOString().slice(0,10)}
function isThisMonth(date:string){return date.slice(0,7)===new Date().toISOString().slice(0,7)}
export function Dashboard({records,onQuickAdd,onGoAccounting}:{records:Transaction[];onQuickAdd:(type:TransactionType)=>void;onGoAccounting:()=>void}){
 const todayIncome=records.filter(r=>r.type==='income'&&isToday(r.date)).reduce((s,r)=>s+r.amount,0);
 const todayExpense=records.filter(r=>r.type==='expense'&&isToday(r.date)).reduce((s,r)=>s+r.amount,0);
 const monthBalance=records.filter(r=>isThisMonth(r.date)).reduce((s,r)=>s+(r.type==='income'?r.amount:-r.amount),0);
 return <main style={{display:'flex',flexDirection:'column',gap:18}}><section className="card" style={{position:'relative',overflow:'hidden'}}><div style={{position:'absolute',right:-20,top:-26,fontSize:140,fontWeight:900,color:'rgba(156,106,70,.08)',fontFamily:'var(--font-number)'}}>X</div><div style={{display:'flex',alignItems:'center',gap:12,position:'relative'}}><div className="logo-x"><span>X</span></div><div><div className="brand-title">記帳天地</div><div style={{color:'var(--muted)',fontWeight:700}}>{greeting()}，今天也要好好生活。</div></div></div><p style={{position:'relative',margin:'18px 0 0',color:'var(--muted)',lineHeight:1.7}}>把每一筆生活留下，未來會更清楚。</p></section><section style={{display:'grid',gridTemplateColumns:'1fr',gap:12}}><Summary title="今日收入" amount={todayIncome} tone="income"/><Summary title="今日支出" amount={todayExpense} tone="expense"/><Summary title="本月結餘" amount={monthBalance} tone="primary"/></section><section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8}}><h2 className="page-title" style={{margin:0,fontSize:26}}>最近紀錄</h2><button className="tag" onClick={onGoAccounting}>查看全部</button></div><TransactionList records={records} limit={5}/></section><section className="card"><h2 className="page-title" style={{marginTop:0,fontSize:26}}>快速開始</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><button className="btn btn-primary" onClick={()=>onQuickAdd('income')}><Plus size={18}/> 新增收入</button><button className="btn btn-secondary" onClick={()=>onQuickAdd('expense')}><Minus size={18}/> 新增支出</button></div></section></main>
}
function Summary({title,amount,tone}:{title:string;amount:number;tone:'income'|'expense'|'primary'}){const color=tone==='income'?'var(--income)':tone==='expense'?'var(--expense)':'var(--primary)';return <div className="card" style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'18px 20px'}}><div style={{color:'var(--muted)',fontWeight:800}}>{title}</div><div className="amount" style={{fontSize:26,color}}>NT${amount.toLocaleString()}</div></div>}
