import { useEffect, useState } from 'react';
import type { Transaction, TransactionDraft, TransactionType } from '../../types/transaction';
const today = () => new Date().toISOString().slice(0,10);
const defaultCategory = (type: TransactionType) => type === 'income' ? '其他收入' : '日常支出';
export function TransactionSheet({ initialType, editing, onClose, onSave }: { initialType: TransactionType; editing?: Transaction | null; onClose: () => void; onSave: (draft: TransactionDraft, id?: string) => void }) {
  const [draft, setDraft] = useState<TransactionDraft>({ type: initialType, amount: '', category: defaultCategory(initialType), date: today(), note: '' });
  useEffect(() => { if (editing) setDraft({ type: editing.type, amount: String(editing.amount), category: editing.category, date: editing.date, note: editing.note }); }, [editing]);
  const categories = draft.type === 'income' ? ['薪水','營業收入','獎金','投資','其他收入'] : ['餐飲','交通','生活用品','娛樂','房租','日常支出'];
  const submit = () => { if (!draft.amount || Number(draft.amount) <= 0) return alert('請輸入正確金額'); onSave(draft, editing?.id); };
  return <div className="sheet-backdrop" onClick={onClose}><section className="sheet" onClick={(e)=>e.stopPropagation()}><div className="sheet-handle"/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><h2 className="page-title" style={{margin:0}}>{editing ? '編輯紀錄' : '新增紀錄'}</h2><span className="tag">{draft.type === 'income' ? '收入' : '支出'}</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14}}><button className={`btn ${draft.type==='income'?'btn-primary':'btn-secondary'}`} onClick={()=>setDraft({...draft,type:'income',category:defaultCategory('income')})}>收入</button><button className={`btn ${draft.type==='expense'?'btn-primary':'btn-secondary'}`} onClick={()=>setDraft({...draft,type:'expense',category:defaultCategory('expense')})}>支出</button></div><div className="field"><label>金額</label><input inputMode="decimal" placeholder="NT$ 0" value={draft.amount} onChange={(e)=>setDraft({...draft,amount:e.target.value})}/></div><div className="field"><label>分類</label><select value={draft.category} onChange={(e)=>setDraft({...draft,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>日期</label><input type="date" value={draft.date} onChange={(e)=>setDraft({...draft,date:e.target.value})}/></div><div className="field"><label>備註</label><textarea placeholder="留下這筆生活紀錄..." value={draft.note} onChange={(e)=>setDraft({...draft,note:e.target.value})}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><button className="btn btn-secondary" onClick={onClose}>取消</button><button className="btn btn-primary" onClick={submit}>儲存</button></div></section></div>;
}
